language: php

php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls

sudo: false

notifications:
    email: false